### ISSUE TITLE
launch should use $this->storybookViewports

### ISSUE THREAD

**Issue by chrillep** [area17/blast#101]
https://github.com/area17/blast/blob/36ec52b08f859a841819ae9bc1663e01888e688d/src/Commands/Launch.php#L149C21-L149C21

$this->buildTailwindViewports($this->storybookViewports),

---

trait TailwindViewports

should use Illuminate\Support\Arr;

**Comment by mrtimbrook** [comment]
I pushed a [fix](https://github.com/area17/blast/commit/f21899abd6035701db919d438eefa9f290ad5d86) to the `1.x` branch last week. It'll be included in the next release but please use `1.x-dev` in the meantime

**Comment by chrillep** [comment]
@mrtimbrook when is the next release due ? ;) thank u for your time

**Comment by mrtimbrook** [comment]
Sorry, it's been a bit of a crazy end to the year. I'm hoping to dedicate some time to blast over the holidays and get a new version released by the new year! Thanks for your patience :)

**Comment by chrillep** [comment]
sounds great! :)
