### ISSUE TITLE
"The command "'node' './src/resolveTailwindConfig.js'" failed" when executing artisan blast:launch

### ISSUE THREAD

**Issue by SimKlee** [area17/blast#119]
I am using default Laravel 10 and tested also with Laravel 11 after installed Laravel Breeze:

0/2 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░] Reusing npm dependencies...
1/2 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░] Generating Stories...node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/www/html/node_modules/tailwindcss/defaultTheme' imported from /var/www/html/tailwind.config.js
Did you mean to import tailwindcss/defaultTheme.js?
    at finalizeResolution (node:internal/modules/esm/resolve:264:11)
    at moduleResolve (node:internal/modules/esm/resolve:917:10)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///var/www/html/node_modules/tailwindcss/defaultTheme'
}

Node.js v20.11.1

   Symfony\Component\Process\Exception\ProcessFailedException 

  The command "'node' './src/resolveTailwindConfig.js'" failed.

Exit Code: 1(General error)

Working directory: /var/www/html/vendor/area17/blast

Output:
================

Error Output:
================

  at vendor/symfony/process/Process.php:270
    266▕      */
    267▕     public function mustRun(?callable $callback = null, array $env = []): static
    268▕     {
    269▕         if (0 !== $this->run($callback, $env)) {
  ➜ 270▕             throw new ProcessFailedException($this);
    271▕         }
    272▕ 
    273▕         return $this;
    274▕     }

      +27 vendor frames 

  28  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by mrtimbrook** [comment]
For now you will need to add the file extension to the import on line 1 of your project's `tailwind.config.js`. We'll look into a solution to prevent blast from making that requirement.
