### ISSUE TITLE
Laravel Sail Configuration Query: Resolving Error Encountered

### ISSUE THREAD

**Issue by cmayorgahilario** [area17/blast#127]
Hello,

I'm encountering difficulties configuring Laravel Sail as I'm consistently encountering the following error: [insert error message here]. I've followed the instructions provided in the official documentation, yet I'm unable to resolve it.

![image](https://github.com/area17/blast/assets/4119035/4b9bc9ca-4cb5-4e2a-94b8-9bc1f535851d)

use "php artisan blast:launch"

Could someone please provide guidance on the correct configuration to use with Laravel Sail? I appreciate any assistance or suggestions you can offer to help resolve this issue.

Thank you in advance for your collaboration!

**Comment by mrtimbrook** [comment]
It looks like you're trying to access the route used by Storybook to access your components. Go to localhost:6006 to access the Storybook UI.
