### ISSUE TITLE
Addition of source code to Docs tab in Blast view

### ISSUE THREAD

**Issue by RobertAByrnes** [area17/blast#23]
@mrtimbrook Will do, I had a dive into the Storybook docs about this topic earlier,. Will do more digging.  Looks like the dependency is already there.

**Comment by RobertAByrnes** [comment]
<?php

namespace A17\Blast\Commands;

use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;
use A17\Blast\DataStore;
use A17\Blast\Traits\Helpers;
use A17\Blast\Traits\SourceCode;

class GenerateStories extends Command
{
    use Helpers;
    use SourceCode;

**Comment by RobertAByrnes** [comment]
![Capture2](https://user-images.githubusercontent.com/90920797/141009772-04387b8b-995b-49d8-8425-11656f0b2f78.PNG)

**Comment by mrtimbrook** [comment]
This is great, thanks! I'm going to have a play around with it.

**Comment by RobertAByrnes** [comment]
@mrtimbrook  Also try: npm install storybook-source-code-addon

Edit main.js to:

```
module.exports = {
  stories: ['../stories/**/*.stories.mdx', '../stories/**/*.stories.@(json)'],
  addons: [
    '@storybook/addon-postcss',
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-a11y',
    'storybook-addon-designs',
    '@etchteam/storybook-addon-status',
    'storybook-source-code-addon'
  ],
  core: {
    builder: 'webpack5'
  }
};
```
And to allow doc to be rendered in the canvas edit GenerateStories.php to:

```
 private function buildChildTemplate($item)
    {
        $data = [
            'name' => ucwords(
                str_replace('.blade.php', '', $item['name']),
                '/',
            ),
            'parameters' => [
                'server' => [
                    'id' => str_replace('.blade.php', '', $item['path']),
                ],
                'docs' => [
                    'source' => [
                        'code' => $this->fileContents($this->storyViewsPath.'/'.$item['path'])
                    ]
                ],
                'componentSource' => [
                    'code' => $this->fileContents($this->storyViewsPath.'/'.$item['path'])
                ]
            ],
        ];
```

**Comment by mrtimbrook** [comment]
@RobertAByrnes Created a PR - https://github.com/area17/blast/pull/24

**Comment by RobertAByrnes** [comment]
@mrtimbrook Excellent. I was just looking at chopping the @storybook directive
