### ISSUE TITLE
Storybook to reload after component source edit/save

### ISSUE THREAD

**Issue by estudiooka** [area17/blast#36]
Hi there, amazing project , perfect partner for working with Twill.

I instaled in a pre-existing twill instalation. Everything fine, but I would like to devep isolated components working straight in the Storybook as I do with Nuxt. But I can't get it to auto-reload the page when a save the component source changes.

At my laravel build I use the browserSync for Lavavel Mix so I can proxy the Storybook url to get something like this, but I would like to have it straight into the Storybook build. Any way to edit the Blast webpack.config ?

Also, Is there any way to add storybook addons, like the tailwind dark mode ?

Resuming:  the possibly to overwrite the .storybook and webpack without hacking the vendor package would be great.

Big thanks.

**Comment by mrtimbrook** [comment]
Hi. I'm glad to hear you're enjoying Blast!

The auto-reloading is definitely on our list of things to add. If you already have a solution in mind for this I would be happy to review a PR.

Sadly, as of right now there's no way to install addons within Blast. This is also something that we're looking into.
