### ISSUE TITLE
❤️ add ability to set manifest path

### ISSUE THREAD

**Issue by chrillep** [area17/blast#82]
First of love the work!

https://github.com/area17/blast/blob/1c3aaf32e7e788a09c820492fba37dffa074a587/src/BlastServiceProvider.php#L118-L119

we are using wp acorn which is WordPress with Laravel
it generates the manifest file to public/dist instead.

So we would like to be able to config the path of the manifest files

refs:

* https://roots.io/acorn/
* https://bud.js.org/
* https://roots.io/radicle/

**Comment by mrtimbrook** [comment]
I've added it to the list. I'm interested to hear about your experience of using blast with WP Acorn too.

**Comment by mrtimbrook** [comment]
This will be included in the next release

**Comment by chrillep** [comment]
Yay! As far as acorn/radicle goes it works pretty much out of the box!!! 

There is one small annoyance. It's related to how artisan commands are executed. They are initiated via wp cli. So the commands are `wp acorn <artisan command>`. So the listener yarn scripts does not work. Not sure if you can get around it tho without breaking something else . 😀

**Comment by mrtimbrook** [comment]
@chrillep Oh nice! How did you set up the custom routes? I gave it a very quick test but I'm out of the loop on WP right now and I couldn't get the `storybook_preview` route up and running.

If you can send over a demo repo I'd love to take a look at how you've set it all up and see what we can do to get everything working properly

**Comment by chrillep** [comment]
> @chrillep Oh nice! How did you set up the custom routes? I gave it a very quick test but I'm out of the loop on WP right now and I couldn't get the `storybook_preview` route up and running.
> 
> If you can send over a demo repo I'd love to take a look at how you've set it all up and see what we can do to get everything working properly

i believe its a experimental env setting
https://github.com/search?q=org%3Aroots%20ACORN_ENABLE_EXPERIMENTAL_ROUTER&type=code


https://github.com/roots/acorn/blob/c94b27f83002ac12ef42790d1a4cfb270d512c61/src/Roots/Acorn/Application.php#L459-L463

https://github.com/roots/acorn/blob/c94b27f83002ac12ef42790d1a4cfb270d512c61/src/Roots/Acorn/Bootloader.php#L113-L121


im on vacation so not able to test all the new features. Maybe next week when we are back :)

**Comment by chrillep** [comment]
work gr8 btw
