### ISSUE TITLE
❤️ Feat Req: Use tailwind screen sizes for storybook viewports setting

### ISSUE THREAD

**Issue by chrillep** [area17/blast#85]
Since we already have the values from tailwind why not use it in storybook aswell?

refs:
* https://storybook.js.org/docs/react/essentials/viewport
* https://storybook.js.org/docs/react/essentials/viewport#add-new-devices

https://github.com/area17/blast/assets/1267931/f76edae7-de1e-40ab-bb54-5bee8fa6dfbf

**Comment by mrtimbrook** [comment]
This will be included in the next release

**Comment by chrillep** [comment]
On fire! 🙏
