### ISSUE TITLE
💡 Feat Req: support multiple design urls per story

### ISSUE THREAD

**Issue by chrillep** [area17/blast#86]
As per Design addon settings pass array of designs.

https://storybookjs.github.io/addon-designs/?path=/story/docs-advanced-usage--embed-multiple-designs
https://github.com/storybookjs/addon-designs/blob/e09d21d2381752184eb9d442b9b89229d011af65/packages/examples/stories/docs/advanced/index.stories.js#L28-L39

https://storybookjs.github.io/addon-designs/?path=/story/docs-advanced-usage--set-tab-names

https://github.com/storybookjs/addon-designs/blob/e09d21d2381752184eb9d442b9b89229d011af65/packages/examples/stories/docs/advanced/index.stories.js#L43-L56

**Comment by mrtimbrook** [comment]
This will be included in the next release
